services:
    mysql:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - 3306:3306
        networks:
            - sylius


    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # SMTP
            - 8025:8025 # UI
        networks:
            - sylius

networks:
    sylius:
        driver: bridge
